# fly.toml app configuration file generated for mangakg-frontend on 2025-09-08T22:46:20+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mangakg-frontend'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '5s'
    method = 'get'
    path = '/health'
    protocol = 'http'

[[vm]]
  size = 'shared-cpu-1x'
